package com.example.newswebsite.Entity.Enums;

public enum RoleTypes {
    ADD_ROLE, EDIT_ROLE, DELETE_ROLE, READ_ROLE,
    ADD_USER, ADD_COMMENT, ADD_POST,
    EDIT_USER, EDIT_COMMENT, EDIT_POST,
    READ_USER, READ_COMMENT, READ_POST,
    DELETE_USER, DELETE_COMMENT, DELETE_POST,
    DELETE_MY_COMMENT, EDIT_MY_COMMENT
}
